#!/usr/bin/env bash

set -e

SUBVER="${DEBABI:-1}"

WRKDIR="$(mktemp -d)"
CURDIR="$(pwd)"
# Per Debian maintainer's guide, we want to avoid `-` in the upstream version number.
# Since I note development builds similarly to "1.1.0-dev3", I need to transform that
# to "1.1.0~dev3" to maintain compatabiliy with dpkg. A `-` is used to seporate the
# upstream version from the package/ABI version incremented by Debian.
PKGVER="$(cat VERSION | tr '-' '~')-$SUBVER"
PKGDIR="pgalloc_${PKGVER}_amd64"

function cleanup {
    rm -rf "$WRKDIR"

    if [ "$(whoami)" != "root" ]; then
        echo "Did you remember to build with \`fakeroot\` you silly goose?"
        echo "If not, you better know what you are doing."
        exit 1
    fi
}
trap cleanup EXIT

cd "$WRKDIR"
mkdir -p "$PKGDIR"/opt/catloaf/lib

BINDST="$PKGDIR"/opt/catloaf/lib

cp "$CURDIR"/"$BASENAME"."$MAJOR" "$BINDST"/"$BASENAME"."$VERSION_ABI"
cp "$CURDIR"/libpgalloc.a "$BINDST"/

cd "$BINDST"
ln -s "$BASENAME"."$VERSION_ABI" "$BASENAME"."$MAJOR"
ln -s "$BASENAME"."$VERSION_ABI" "$BASENAME"
cd "$WRKDIR"

INCDIR="$PKGDIR"/opt/catloaf/include/pgalloc
mkdir -p "$INCDIR"

cp "$CURDIR"/include/*.h "$INCDIR"/

mkdir -p "$PKGDIR"/DEBIAN

CONTROL="\
Package: pgalloc
Version: $PKGVER
Architecture: amd64
Depends: libc6 (>= 2.31)
Maintainer: Alex Necheff <pkg@necheff.net>
Homepage: https://www.necheff.net
Description: A fast fixed block size memory allocator.
"

echo "$CONTROL" > "$PKGDIR"/DEBIAN/control

dpkg-deb --build "$PKGDIR"
cp "$PKGDIR".deb "$CURDIR"/

